### ISSUE TITLE
smart_variables do not work

### ISSUE THREAD

**Issue by alexalok** [ankane/blazer-docker#10]
Hi,

I've added a few variables to a `smart_variables` section but they don't seem to pick up in the queries. I'm not familiar with Ruby so could you please help me with the troubleshooting steps? I'm using the latest official docker image (docker.io/ankane/blazer@sha256:f127d2ee00fbf43fa4985d9b22568bbacb50862a88b3d2883da9cdb2c29f883f).

My blazer.yaml:

```yaml
data_sources:
  imapp:
    url: # redacted

    smart_variables:
      payment_system: {0: "Reserved", 1: "AppStore", 2: "GooglePlay"}
```

Simple query for testing:
![image](https://user-images.githubusercontent.com/5950085/196119974-256c8f6b-5e9b-4e12-b89c-f762097baabf.png)
Notice that the `payment_system` is not recognized as a smart variable.

Thanks!
